# hyprviz configuration (created automatically)

decoration {

    shadow {
        enabled = true
    }

    fullscreen_opacity = 1
    inactive_opacity = 1
    dim_inactive = false

    blur {
        xray = true
    }

}